name: Makepad
options:
  bundleIdPrefix: com.makepad
configs:
    Debug: debug
    Release: release
targets:
  Makepad_iOS:
    type: application
    platform: iOS
    deploymentTarget: "12.2"
    sources: src
    scheme:
      environmentVariables:
        - variable: RUST_BACKTRACE
          value: 1
          isEnabled: true
    settings:
      base:
          OTHER_LDFLAGS:
            - $(inherited)
            - -lmakepad
            - -framework Security
            - -framework Foundation
            - -framework UIKit
            - -framework CoreGraphics
            - -framework Metal
          ENABLE_BITCODE: NO
          CLANG_CXX_LANGUAGE_STANDARD: c++14
          CLANG_CXX_LIBRARY: libc++
      configs:
        debug:
            HEADER_SEARCH_PATHS: ["$(inherited)", "./src"]
            LIBRARY_SEARCH_PATHS: ["$(inherited)", "./target/universal/debug"]
        release:
            HEADER_SEARCH_PATHS: ["$(inherited)", "./src"]
            LIBRARY_SEARCH_PATHS: ["$(inherited)", "./target/universal/release"]
    dependencies:
      - sdk: libresolv.tbd
      - sdk: libc++.tbd
        embed: false  
    info:
        path: src/Info.plist
        properties:
            UILaunchStoryboardName: LaunchScreen